name: build exe
on:
  workflow_dispatch:
jobs:
  pack:
    name: bundling & packing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.18.0
      - name: 'Install Dependencies'
        run: npm install
      - name: 'Bundling with esbuild'
        run: npx esbuild index.js --bundle --platform=node --external:canvas --outfile=dist/index.js
      - name: 'Packaging with pkg'
        run: npx pkg --compress GZip -t node14-win dist/index.js
      - name: get version action
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ github.token }}
          tag_prefix: "v"
          tag_template: "yyyy.mm.dd.i"
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            draft: false
            prerelease: false
            tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
            release_name: Release ${{ steps.get-version.outputs.version}} ${{ steps.generate_release_tag.outputs.next_release_tag }}
      - name: 'Upload Release'
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ github.token }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./index.exe
         asset_name: expand.exe
         asset_content_type: application/exe
#       - name: Upload server release
#         uses: svenstaro/upload-release-action@v2
#         with:
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           file: '**/*.exe'
#           file_glob: true
#           tag: ${{ github.ref }}
#           overwrite: true
#       - uses: actions/upload-artifact@v2
#         with:
#           name: distributables
#           path: dist/*
#           if-no-files-found: error
#       - uses: actions/upload-artifact@v2
#         with:
#           name: executeable
#           path: '**/*.exe'
#           if-no-files-found: error
#   publish:
#     name: Publish a release
#     runs-on: "ubuntu-18.04"
#     needs:
#       - pack
#     steps:
#       - name: Get our distributables
#         uses: actions/download-artifact@v2
#         with:
#           name: executeable
#           path: exe